language: node_js

# workaround for obsolete `temp` module 0.6
env:
  global:
    - TMPDIR=/tmp
    - COVERALLS_REPO_TOKEN=zSbPkOBuZrK6NktxXW1ZzVEPOUDr9ePpN

node_js:
 - '6'
 - '8'

sudo: false

services:
 - memcached

notifications:
  email:
    jrgm@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#fxa-bots"
    use_notice: false
    skip_join: false

before_install:
  - npm config set spin false

script:
  - grunt nsp --force
  - npm run outdated
  - node_modules/.bin/grunt lint copyright || exit 1
  # use TAP to send coverage to coveralls
  - node_modules/.bin/tap -R spec test/local test/remote --coverage --cov
